In [1]:
import numpy as np

In [2]:
#ejercicio 1
matriz = np.arange(1,26).reshape(5,5)
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
#ejercicio 1.2
submatriz = matriz[1:4, 1:4]
print(submatriz)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [4]:
#ejericcio 1.3
ultimaColumna = matriz [:, -1]
print(ultimaColumna)

[ 5 10 15 20 25]


In [5]:
#ejercicio 2
ventas = np.array([
    [1500, 2000, 1800, 2200],
    [1100, 1300, 1200, 1500],
    [3000, 3100, 2900, 3500]
])

#centa total
ventaTotal = np.sum(ventas)
print(ventaTotal)

#promedio por semana
promedioSemanal = np.mean(ventas, axis = 0)
print(promedioSemanal)

#venta max por sucursal
maxSucursal = np.max(ventas, axis = 1)
print(maxSucursal)

25100
[1866.66666667 2133.33333333 1966.66666667 2400.        ]
[2200 1500 3500]


In [6]:
#ejercicio 3
numeros = np.arange(1,21)
print (numeros)

#mascara de pares
mascaraPares = numeros % 2 == 0
print(mascaraPares)

#aplicar mascara
pares = numeros[mascaraPares]
print(pares)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
#ejercicio 4
edades = np.array([22, 55, 34, 19, 45, 61, 28, 30, 42])

#personas netre 30 y 50
filtro = (edades >=30) & (edades <= 50)
resultado = edades[filtro]
print(resultado)

#menores de 25 o mayores de 55
segundoFiltro = (edades < 25) | (edades > 55)
segundoResultado = edades[segundoFiltro]
print(segundoResultado)

[34 45 30 42]
[22 19 61]


In [8]:
#ejercicio 5
matriz = np.zeros((4,4))
print(matriz)

#modificar bloque central 
matriz[1:3,1:3] = 9
print(matriz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 9. 9. 0.]
 [0. 9. 9. 0.]
 [0. 0. 0. 0.]]


In [11]:
#ejercicio 6
calificaciones = np.random.randint(1,11,50)
print(calificaciones)

#promedio general
promedio = np.mean(calificaciones)
print("Promedio general: ", promedio)

#desaprobados
desaprobados = calificaciones[calificaciones < 4]
print("Cantidad de desaprobados: ", desaprobados.size)

#reemplazar notas
calificaciones[calificaciones < 4] = 4

print(calificaciones)

[ 3  3  5  6  1  1  8  5  7  4  4  1  8  2 10  8  2  7 10  1  1  1 10 10
  2  6  5  3  5  2  5  2  8  5  4  3  9  3  1  4  6  8  1  8 10  4  1  6
  6  3]
Promedio general:  4.76
Cantidad de desaprobados:  20
[ 4  4  5  6  4  4  8  5  7  4  4  4  8  4 10  8  4  7 10  4  4  4 10 10
  4  6  5  4  5  4  5  4  8  5  4  4  9  4  4  4  6  8  4  8 10  4  4  6
  6  4]
