In [1]:
import numpy as np

In [2]:
edades = np.array([22, 25, 30, 35, 40])

print("Dimensiones:", edades.ndim)
print("Forma:", edades.shape)
print("Tipo de datos:", edades.dtype)

edadesFloat = edades.astype(np.float64)
print("Array con tipo de datos float64:", edadesFloat)
print("Nuevo tipo de dato:", edadesFloat.dtype)

Dimensiones: 1
Forma: (5,)
Tipo de datos: int64
Array con tipo de datos float64: [22. 25. 30. 35. 40.]
Nuevo tipo de dato: float64


In [3]:
#Ejercicio 2
idClientes = np.arange(1, 101)

puntosGraficos = np.linspace(0, 10, 50)

print("Primeros 10IDs:", idClientes[:10])
print("Primeros 10 puntos gráficos:", puntosGraficos[:10])

Primeros 10IDs: [ 1  2  3  4  5  6  7  8  9 10]
Primeros 10 puntos gráficos: [0.         0.20408163 0.40816327 0.6122449  0.81632653 1.02040816
 1.2244898  1.42857143 1.63265306 1.83673469]


In [4]:
#Ejercicio 3
matrizAleatoria = np.random.rand(3, 4)

matrizDeUnos = np.ones((3,4))

print("Matriz aleatoria:\n", matrizAleatoria)
print("Matriz de unos:\n", matrizDeUnos)

Matriz aleatoria:
 [[1.02670234e-02 8.53453543e-01 8.67981144e-05 1.11556624e-01]
 [9.25513942e-01 9.32584816e-01 5.20806688e-01 2.77669122e-01]
 [3.03646135e-01 1.74088448e-02 6.21607692e-02 9.10403235e-01]]
Matriz de unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
#Ejercicio 4
sucursales = int(input("Ingrese el número de sucursales: "))
productos = int(input("Ingrese el número de productos: "))

inventario = np.zeros((sucursales, productos), dtype = int)

print ("\nBase de datos de inventario inicializada correctamente")
print("Matriz de inventario (sucursales x productos):\n", inventario)


Base de datos de inventario inicializada correctamente
Matriz de inventario (sucursales x productos):
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]]


In [6]:
#Ejercicio 5 
vector = np.arange(1, 13)
print ("Vector original:", vector)

matriz = vector.reshape(3, 4)
print("Matriz reshaped (3x4):\n", matriz)
print ("Nueva matriz despues del reshape:", matriz.ndim)

Vector original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Nueva matriz despues del reshape: 2


In [7]:
#Ejercicio 6
temperaturas = np.array([15.5, 20.3, 25.1, 30.0, 35.2])
print("Tipo de datos original:", temperaturas.dtype)

temperaturasInt = temperaturas.astype(np.int32)
print("Array con tipo de datos int32:", temperaturasInt)
print("Nuevo tipo de dato:", temperaturasInt.dtype)

Tipo de datos original: float64
Array con tipo de datos int32: [15 20 25 30 35]
Nuevo tipo de dato: int32


In [8]:
#Ejercicio 7
tiradas = np.random.randint(low=1, high=7, size=10)
print("Tiradas de dados:", tiradas)

Tiradas de dados: [6 5 1 3 1 3 5 2 2 5]


In [ ]:
#Ejercicio 8 
humedadTexto = np.array(["45.2", "48.1", "42.5", "50.0"])

humedadNumerica = humedadTexto.astype(np.float64)
print("Suma de humedad (como números):", humedadNumerica.sum())

Suma de humedad (como números): 185.8


In [11]:
#Ejercicio 9 
matriz = np.eye(4)
print("Matriz identidad 4x4:\n", matriz)

resultado = matriz * 5
print("Matriz identidad multiplicada por 5:\n", resultado)

Matriz identidad 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriz identidad multiplicada por 5:
 [[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
